export const heros = [
  {
    img: "/hero/01.png",
    name: "",
    camp: "light",
    Character: "Royal Master",
    Gender: "Male",
    Level: "Holy",
    Weapon: "Gamma Cannon",
    Body: "Blue",
    Pants: "Royal Pants",
    Clothing: "Royal Clothing",
    Decorate: "Golden",
    Mask: "Golden",
    date: "02001",
  },
  {
    img: "/hero/02.png",
    name: "",
    camp: "light",
    Character: "Royal Mage",
    Gender: "Male",
    Level: "Legendary",
    Weapon: "Royal Staff",
    Body: "Purple",
    Pants: "Golden",
    Clothing: "Golden",
    Decorate: "Cloak Brown",
    Mask: "Glasses",
    date: "03002",
  },
  {
    img: "/hero/03.png",
    name: "",
    camp: "light",
    Character: "Berserker",
    Gender: "Female",
    Level: "Legendary",
    Weapon: "BTC Axe",
    Body: "Brown",
    Pants: "Grey",
    Clothing: "Red",
    Decorate: "Hair Pink",
    Mask: "Green",
    date: "09001",
  },
  {
    img: "/hero/04.png",
    name: "",
    camp: "light",
    Character: "Guard Soldier",
    Gender: "Male",
    Level: "Epic",
    Weapon: "Guardian Axe",
    Body: "Green",
    Pants: "Red",
    Clothing: "Red",
    Decorate: "Red",
    Mask: "",
    date: "13002",
  },
  {
    img: "/hero/05.png",
    name: "",
    camp: "light",
    Character: "Miner",
    Gender: "Male",
    Level: "Rare",
    Weapon: "BTC Pick",
    Body: "Purple",
    Pants: "Brown",
    Clothing: "Brown",
    Decorate: "Glasses Orange",
    Mask: "",
    date: "03802",
  },
  {
    img: "/hero/06.png",
    name: "",
    camp: "light",
    Character: "Berserker",
    Gender: "Male",
    Level: "Rare",
    Weapon: "Hook",
    Body: "Orange",
    Pants: "Brown",
    Clothing: "Brown",
    Decorate: "Grey",
    Mask: "",
    date: "33002",
  },
  {
    img: "/hero/07.png",
    name: "",
    camp: "light",
    Character: "Warrior",
    Gender: "Male",
    Level: "Rare",
    Weapon: "Fish Fork",
    Body: "Brown",
    Pants: "Brown",
    Clothing: "Red",
    Decorate: "Earrings",
    Mask: "Yellow",
    date: "03809",
  },
  {
    img: "/hero/08.png",
    name: "",
    camp: "light",
    Character: "Death Knight",
    Gender: "Male",
    Level: "Legendary",
    Weapon: "Death Axe",
    Body: "Yellow",
    Pants: "Yellow",
    Clothing: "Red",
    Decorate: "Red",
    Mask: "",
    date: "56002",
  },
  {
    img: "/hero/09.png",
    name: "",
    camp: "light",
    Character: "Miner",
    Gender: "Female",
    Level: "Legendary",
    Weapon: "Spade Blue",
    Body: "Red",
    Pants: "Yellow",
    Clothing: "Brown",
    Decorate: "Hair Pink",
    Mask: "Brown",
    date: "56602",
  },
  {
    img: "/hero/10.png",
    name: "",
    camp: "light",
    Character: "Undead Warrior",
    Gender: "Male",
    Level: "Holy",
    Weapon: "Giant Axe",
    Body: "Black",
    Pants: "Red",
    Clothing: "Red",
    Decorate: "Red",
    Mask: "Red",
    date: "16062",
  },
  {
    img: "/hero/11.png",
    name: "",
    camp: "light",
    Character: "Blood Warrior",
    Gender: "Male",
    Level: "Epic",
    Weapon: "Katana Red",
    Body: "Red",
    Pants: "Green",
    Clothing: "Green",
    Decorate: "Green",
    Mask: "Green",
    date: "56432",
  },
  {
    img: "/hero/12.png",
    name: "",
    camp: "light",
    Character: "Miner",
    Gender: "Male",
    Level: "Rare",
    Weapon: "Trident",
    Body: "Blue",
    Pants: "Green",
    Clothing: "Green",
    Decorate: "Earrings",
    Mask: "",
    date: "16806",
  },
];
